### ISSUE TITLE
Add graphical tool for KDE

### ISSUE THREAD

**Issue by alex1701c** [alesguzik/linux_detect_tablet_mode#17]
Hello There!

I just tried this for fun on my Lenovo Thinkpad X1 Yoga and it worked really well, thanks!.

I have an idea on how to improve this project: How about adding a KCM (KDE configuration module). This  could be in a sub directory so that users can install it, but don't have to.

This way the users can configure the config file graphically with the native tools.

Edit: It is almost finsihed, see https://github.com/alex1701c/linux_detect_tablet_mode/tree/master/kde.

**Comment by alesguzik** [comment]
Hi. This project was meant for a minimalistic setup with a window manager, not as something for consumption by KDE or Gnome. That's why it's just a simple ruby script. Also, I'm not a C++/Qt developer, so I don't think there's a reason to have it in this repository, as I won't be able to maintain it. But I don't see why your project couldn't coexist with mine as two separate projects.
