### ISSUE TITLE
Installement

### ISSUE THREAD

**Issue by Jensevent** [alesguzik/linux_detect_tablet_mode#3]
Hello,
I know this tab is meant for issues but i was wondering if someone could help me with the installment.
I managed to install ruby yet the rest of the steps seem unclear to me.
Where en what file should i copy?
What config do i need to use?
Which file is ~/.xinitrc?

I would greatly appreciate the help.

**Comment by alesguzik** [comment]
I'm sorry, but to use this you must understand at least basics of linux. `~` stands for your home directory, something like `/home/jensevent`. When you open a terminal most likely your current directory is already set to your home directory.

You need to clone the whole repository (`git clone https://github.com/alesguzik/linux_detect_tablet_mode.git`), not copy individual files or download zip archive, as in that case scripts won't have executable permission bits set, and you will have to fix that manually. After you cloned the repository, you need to copy `watch_tablet.yml` file from it into `.config` directory, which must be inside your home directory. Because it's name starts with `.` it is hidden, so by default you won't be able to see it in your file manager and you'll need to tick "show hidden files" somewhere. If the laptop you are using is exactly the same as mine (X1 Yoga Gen 2) then you probably won't need to edit the script. Otherwise you'll need to find ids of your input devices (run `xinput` in your terminal and read through its output) and change the config to use ids that you have found instead of ones that are for my laptop.

`~/.xinitrc` is a script that is executed when your desktop session starts (when you log in). Read about it here: https://wiki.archlinux.org/index.php/Xinit . You'll need to edit it (or maybe create) so it would contain a line like `/home/jensevent/Projects/linux_detect_tablet_mode/watch_tablet &` (change it accordingly to where you have cloned the repo). `&` at the end means to run it in the background. If you will forget it your desktop environment won't start, as it will be waiting for this script to finish, which it won't do as it is supposed to be running all the time. Before adding it to `.xinitrc` please ensure that it actually works. For that you should run it in a terminal (you'll be able to terminate it with Ctrl+C). If when you start it it will say "Switching to laptop mode", then it have started successfully. After that you may try flipping your laptop to tablet mode. If it works, it should display "Switching to tablet mode".

Keep in mind that if your laptop doesn't have 2 accelerometers (I don't think most of them do), then this set of scripts will be useless for you. If you wish to learn linux I'd suggest you to try Archlinux (https://wiki.archlinux.org/index.php/Installation_guide), at least that's how I learned the basics many years ago. It has got excellent wiki that explains most of the things you may wish to know.

**Comment by Jensevent** [comment]
It turns out my system only has 1 accelerometer, not 2. I greatly appreciate your help tho! Thank you for helping me. I hope this "Issue" will still help others.
