### ISSUE TITLE
Does your script support other modes (stand and tent) ?

### ISSUE THREAD

**Issue by Tuxman2** [alesguzik/linux_detect_tablet_mode#8]
Hi,

Thanks for your work.

Does your script support other modes (stand and tent) ?

Regards.

**Comment by alesguzik** [comment]
Stand is the same as tablet (normal screen orientation and disabled keyboard). Tent is tablet + flip the screen. Flipping the screen depending on the accelerometer could be implemented, but I personally prefer flipping the screen explicitly. If it would be implemented, I think it would be better kept in a separate script, as it needs one accelerometer instead of 2, and that functionality is independent of disabling bottom part of the laptop when it's bent over.
